<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Dapper" Version="2.1.89" />
    <PackageVersion Include="Dapper.AOT" Version="1.0.52" />
    <PackageVersion Include="Microsoft.Data.Sqlite.Core" Version="10.0.12" />
    <PackageVersion Include="SQLitePCLRaw.bundle_winsqlite3" Version="2.1.11" />
    <PackageVersion Include="SQLitePCLRaw.bundle_sqlite3" Version="2.1.11" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageVersion Include="System.CommandLine" Version="2.0.12" />
    <PackageVersion Include="YamlDotNet" Version="18.1.0" />
    <PackageVersion Include="Moq" Version="4.21.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageVersion Include="NUnit" Version="4.6.1" />
    <PackageVersion Include="NUnit3TestAdapter" Version="6.3.0" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
  </ItemGroup>
</Project>
